services:
  - type: web
    name: cdphotografy-API
    env: ruby
    plan: free
    buildCommand: "bundle install && rails db:migrate && rails assets:precompile"
    startCommand: "bundle exec rails server -p $PORT"
    envVars:
      - key: DATABASE_URL
        value: postgres://cdphotografy_api_user:LS8SLfDoqREdkbAUtFAy4k6RDiwThlS1@dpg-cpf12r7109ks73bbth30-a:5432/cdphotografy_api
      - key: SECRET_KEY_BASE
        value: 1ac87055c5e92ccf2c19b4f95a56fef74c58e40342d5808b28b15069a011dbcd249261fe761cd69a7cc030e89a02e5da7e4292
      - key: CLOUDINARY_CLOUD_NAME
        value: dcvtrregd
      - key: CLOUDINARY_API_KEY
        value: 346958436335447
      - key: CLOUDINARY_API_SECRET
        value: RxPAJtKtOydFvGy9pOabWoZhAzM
